'use strict';
const E=CarbonEngine,$=id=>document.getElementById(id),form=$('workspace');
const fmt=(n,d=2)=>n.toLocaleString('ko-KR',{maximumFractionDigits:d});
let map,marker,boundary,greenLayer,vertices=[],records=[],groupId=0,locationSource='미등록',lastGreenPosition=null,mapSource='ArcGIS World Imagery';
const key='withu-admin-v2';
function note(text,error=false){$('message').textContent=text;$('message').classList.toggle('error',error);}
function input(label,name,min,max,value=''){const wrap=document.createElement('label');wrap.textContent=label;const el=document.createElement('input');el.type='number';el.dataset.key=name;el.min=min;el.max=max;el.step=name.startsWith('n')?'1':'any';el.value=value;wrap.append(el);return wrap;}
function addTree(data={}){const box=document.createElement('div');box.className='tree-group';box.dataset.group=++groupId;const head=document.createElement('div');head.className='group-head';const label=document.createElement('label');label.textContent='수종명';const species=document.createElement('input');species.dataset.key='species';species.maxLength=80;species.placeholder='예: 소나무';species.value=data.species||'';label.append(species);const remove=document.createElement('button');remove.type='button';remove.className='remove';remove.textContent='그룹 삭제';remove.onclick=()=>{box.remove();render();};head.append(label,remove);box.append(head);const periods=document.createElement('div');periods.className='grid two';for(let t=0;t<2;t++){const period=document.createElement('div');period.className='tree-period';const h=document.createElement('h3');h.textContent=t?'현재 조사':'기준 조사';period.append(h);const grid=document.createElement('div');grid.className='grid three';for(const [name,text,min,max] of [['n','수량 (그루)',0,10000000],['d','평균 DBH (cm)',.01,1000],['h','평균 수고 (m)',.01,150]])grid.append(input(text,name+t,min,max,data[name+t]??''));period.append(grid);periods.append(period);}box.append(periods);const details=document.createElement('details'),summary=document.createElement('summary');summary.textContent='계수 설정 · 기존 프로젝트의 공통 기본값';details.append(summary);const help=document.createElement('p');help.className='help';help.textContent='수종명만 변경해도 계수가 자동 변경되지는 않습니다. 검증된 수종별 계수가 있다면 직접 수정하세요.';details.append(help);const grid=document.createElement('div');grid.className='grid three';for(const [name,text,min,max,value] of [['density','목재 기본밀도 (kg/m³)',1,2000,500],['f','형수 F',.01,1,.45],['bef','확장계수 BEF',1,5,1.3],['r','뿌리/지상부 비 R',0,3,.25],['cf','탄소분율 CF',.01,1,.5]])grid.append(input(text,name,min,max,data[name]??value));details.append(grid);box.append(details);$('tree-groups').append(box);}
function groups(){return [...document.querySelectorAll('.tree-group')].map(box=>Object.fromEntries([...box.querySelectorAll('[data-key]')].map(el=>[el.dataset.key,el.value])));}
function position(){try{return [E.number($('lat').value,-85,85,'위도'),E.number($('lon').value,-180,180,'경도')];}catch{return null;}}
function distanceKm(a,b){const rad=Math.PI/180,dLat=(b[0]-a[0])*rad,dLon=(b[1]-a[1])*rad,x=Math.sin(dLat/2)**2+Math.cos(a[0]*rad)*Math.cos(b[0]*rad)*Math.sin(dLon/2)**2;return 12742*Math.asin(Math.min(1,Math.sqrt(x)));}
function getArea(){if(vertices.length<3)return null;const p=position();if(!p)throw Error('장치 좌표를 먼저 등록하세요.');if(vertices.some(v=>distanceKm(p,v)>5))throw Error('경계점은 장치에서 5 km 이내로 지정하세요.');return E.polygon(vertices.map(v=>v.join(',')).join('\n')).area;}
function paintMap(){if(!map)return;if(marker)map.removeLayer(marker);if(boundary)map.removeLayer(boundary);const p=position();marker=p?L.circleMarker(p,{radius:9,color:'#fff',weight:3,fillColor:'#176b70',fillOpacity:1}).addTo(map).bindPopup('등록 장치 · '+$('device').value):null;if(vertices.length){const points=vertices.map(v=>L.circleMarker(v,{radius:5,color:'#176b70',weight:2,fillColor:'#fff',fillOpacity:1}));if(vertices.length>1)points.push(vertices.length>2?L.polygon(vertices,{color:'#176b70',weight:3,fillColor:'#23a987',fillOpacity:.23}):L.polyline(vertices,{color:'#176b70',weight:3}));boundary=L.layerGroup(points).addTo(map);}else boundary=null;}
function renderArea(){const p=position();$('gps-value').textContent=p?`${p[0].toFixed(6)}, ${p[1].toFixed(6)}`:'좌표 등록 필요';$('device-status').textContent=p?`장치 좌표 · ${locationSource}`:'위치 미등록';$('point-count').textContent=`경계점 ${vertices.length}개`;if(lastGreenPosition&&(!p||distanceKm(p,lastGreenPosition)>.005)){lastGreenPosition=null;$('green-value').textContent='— m²';$('green-detail').textContent='좌표가 변경되었습니다. 다시 추산하세요.';if(greenLayer&&map){map.removeLayer(greenLayer);greenLayer=null;}}try{const a=getArea();$('area-value').textContent=a==null?'— m²':fmt(a,1)+' m²';$('area-detail').textContent=a==null?'위성영상에서 녹지 경계를 순서대로 3점 이상 클릭하세요.':`${fmt(a/10000,4)} ha · ${mapSource} 영상에서 수동 지정한 근사 면적`;}catch(err){$('area-value').textContent='— m²';$('area-detail').textContent=err.message;}paintMap();}
function initMap(){if(!window.L){$('map-unavailable').hidden=false;return;}map=L.map('map',{maxZoom:19}).setView([36.4,127.8],7);const imagery=L.tileLayer('https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}',{maxZoom:19,attribution:'Imagery © Esri, Vantor, Earthstar Geographics, GIS User Community'}).addTo(map);const historic=L.tileLayer('https://tiles.maps.eox.at/wmts/1.0.0/s2cloudless_3857/default/g/{z}/{y}/{x}.jpg',{maxZoom:19,maxNativeZoom:14,attribution:'© EOX · modified Copernicus Sentinel data 2016 & 2017'});L.control.layers({'고해상도 항공·위성 영상':imagery,'Sentinel-2 2016 비교 영상':historic},null,{collapsed:false,position:'topright'}).addTo(map);imagery.on('tileerror',()=>$('map-unavailable').hidden=false);imagery.on('tileload',()=>$('map-unavailable').hidden=true);map.on('baselayerchange',event=>{mapSource=event.layer===imagery?'ArcGIS World Imagery':'Sentinel-2 2016';renderArea();});map.on('click',event=>{const p=position();if(!p){note('장치 위도·경도를 먼저 등록하세요.',true);return;}const v=[event.latlng.lat,event.latlng.lng];if(distanceKm(p,v)>5){note('장치에서 5 km 이내의 경계를 선택하세요.',true);return;}if(vertices.length>=500){note('경계점은 최대 500개입니다.',true);return;}vertices.push(v);render();});const p=position();if(p)map.setView(p,16);paintMap();}
function sensorCards(){const latest=records[0];$('sensor-cards').replaceChildren();for(const [name,label,unit] of [['soil_temperature','토양 온도','°C'],['soil_moisture','토양 수분','%'],['soil_ec','전기전도도 EC','µS/cm'],['soil_ph','산도 pH','pH']]){const card=document.createElement('article'),title=document.createElement('p'),value=document.createElement('strong'),small=document.createElement('small');title.textContent=label;value.textContent=latest?.[name]==null?'—':fmt(latest[name],name==='soil_ec'?0:1);small.textContent=latest?.[name]==null?'미수집':unit;card.append(title,value,small);$('sensor-cards').append(card);}if(!latest){$('sensor-meta').textContent='실제 서버 기록 연결 대기';$('sensor-history').replaceChildren();$('history-status').textContent='기록 없음';return;}$('sensor-meta').textContent=`${latest.device_id} · 마지막 측정 ${new Date(latest.timestamp).toLocaleString('ko-KR')} · ${latest.source==='simulation'?'시뮬레이션 기록':'장치 기록'}`;const buckets=new Map();for(const row of records){const time=Date.parse(row.timestamp);if(!Number.isFinite(time))continue;const bucket=Math.floor(time/21600000);if(!buckets.has(bucket))buckets.set(bucket,row);if(buckets.size>=12)break;}$('sensor-history').replaceChildren(...[...buckets.values()].map(row=>{const item=document.createElement('div');item.className='history-row';const time=document.createElement('strong'),values=document.createElement('span');time.textContent=new Date(row.timestamp).toLocaleString('ko-KR');values.textContent=`온도 ${row.soil_temperature==null?'—':fmt(row.soil_temperature,1)+' °C'} · 수분 ${row.soil_moisture==null?'—':fmt(row.soil_moisture,1)+' %'} · EC ${row.soil_ec==null?'미수집':fmt(row.soil_ec,0)+' µS/cm'} · pH ${row.soil_ph==null?'미수집':fmt(row.soil_ph,1)}`;item.append(time,values);return item;}));$('history-status').textContent=`최근 ${buckets.size}개 6시간 구간`;}
async function refresh(){const token=$('admin-token').value.trim();if(!token){note('관리자 조회 토큰이 준비되면 입력하세요. 현재 연결 대기 상태입니다.',true);return;}const button=$('refresh-readings');button.disabled=true;$('sensor-source').textContent='서버 조회 중';try{const response=await fetch('/api/admin-readings?device='+encodeURIComponent($('device').value),{headers:{Authorization:'Bearer '+token},cache:'no-store'});let payload={};try{payload=await response.json();}catch{}if(!response.ok)throw Error(payload.error||`조회 실패 (${response.status})`);records=(Array.isArray(payload.records)?payload.records:[]).map(E.sensor).filter(row=>row.device_id===$('device').value).sort((a,b)=>Date.parse(b.timestamp)-Date.parse(a.timestamp));sensorCards();$('sensor-source').textContent=records.length?'장치 기록 조회됨':'기록 없음';note(records.length?`장치 기록 ${records.length}건을 확인했습니다.`:'서버에 이 장치의 기록이 없습니다.');}catch(err){records=[];sensorCards();$('sensor-source').textContent='서버 연결 대기';note(err.message,true);}finally{button.disabled=false;}}
function render(){renderArea();const data=groups(),errors=[];let current=null,baseline=null,years=null;try{years=E.years($('date0').value,$('date1').value);}catch(err){errors.push(err.message);}for(let t=0;t<2;t++){try{if(!data.length)throw Error('수종 그룹을 추가하세요.');let sum=0;for(const group of data){if(!group.species.trim())throw Error('수종명을 입력하세요.');sum+=E.tree(group,t);}if(t)current=sum;else baseline=sum;}catch(err){errors.push(`${t?'현재':'기준'} 수목: ${err.message}`);}}$('tree-stock').textContent=current==null?'산정 대기':fmt(current,3)+' tCO₂';$('annual').textContent=years==null||current==null||baseline==null?'산정 대기':fmt((current-baseline)/years,3)+' tCO₂/년';const lines=[];if(current!=null&&baseline!=null)lines.push(`조사 기간 수목 저장량 변화: ${fmt(current-baseline,3)} tCO₂`);if(years!=null)lines.push(`조사 간격: ${fmt(years,2)}년`);try{const a=getArea();if(a!=null)lines.push(`위성영상 경계 면적: ${fmt(a,1)} m² (수목 저장량 식에 재승산하지 않음)`);}catch(err){errors.push(err.message);}$('breakdown').replaceChildren(...[...lines,...new Set(errors)].map(line=>{const p=document.createElement('p');p.textContent=line;return p;}));}
function snapshot(){return {version:2,device:$('device').value,lat:$('lat').value,lon:$('lon').value,vertices,dates:[$('date0').value,$('date1').value],groups:groups()};}
function restore(data){if(data?.version!==2||!Array.isArray(data.groups)||data.groups.length>50||!Array.isArray(data.vertices)||data.vertices.length>500)throw Error('저장 형식 오류');$('device').value='pi5-monitor-01';$('lat').value=data.lat??'';$('lon').value=data.lon??'';vertices=data.vertices.filter(p=>Array.isArray(p)&&p.length===2&&p.every(Number.isFinite));$('date0').value=data.dates?.[0]||'';$('date1').value=data.dates?.[1]||'';$('tree-groups').replaceChildren();data.groups.forEach(addTree);if(!data.groups.length)addTree();render();}
function setPosition(lat,lon,source){$('lat').value=Number(lat).toFixed(7);$('lon').value=Number(lon).toFixed(7);locationSource=source;const p=position();if(map&&p)map.setView(p,16);render();}
async function locationRequest(method,body){const token=$('admin-token').value.trim();if(!token)throw Error('관리자 조회 토큰을 입력하세요.');const response=await fetch('/api/admin-location?device='+encodeURIComponent($('device').value),{method,headers:{Authorization:'Bearer '+token,...(body?{'Content-Type':'application/json'}:{})},body:body?JSON.stringify(body):undefined,cache:'no-store'});let payload={};try{payload=await response.json();}catch{}if(!response.ok)throw Error(payload.error||`위치 요청 실패 (${response.status})`);return payload;}
async function refreshLocation(){try{const payload=await locationRequest('GET');if(!payload.location){$('location-source').textContent='서버에 위치 미등록';note('이 장치의 서버 위치 기록이 없습니다.');return;}const loc=payload.location;setPosition(loc.latitude,loc.longitude,loc.source==='gpsd'?'장치 GPS · 서버':'관리자 등록 · 서버');$('location-source').textContent=`${loc.source==='gpsd'?'장치 GPS':'관리자 등록'} · ${new Date(loc.updated_at).toLocaleString('ko-KR')}`;note('서버의 장치 위치를 조회했습니다.');}catch(err){$('location-source').textContent='서버 위치 연결 대기';note(err.message,true);}}
async function publishLocation(){const p=position();if(!p){note('먼저 장치 좌표를 입력하세요.',true);return;}try{const payload=await locationRequest('PUT',{latitude:p[0],longitude:p[1],source:'admin'});setPosition(payload.location.latitude,payload.location.longitude,'관리자 등록 · 서버');$('location-source').textContent='관리자 등록 · 서버';note('장치 위치를 서버에 등록했습니다.');}catch(err){note(err.message,true);}}
function browserLocation(){if(!navigator.geolocation){note('이 브라우저에서 위치 기능을 사용할 수 없습니다.',true);return;}navigator.geolocation.getCurrentPosition(result=>{setPosition(result.coords.latitude,result.coords.longitude,'현장 브라우저 · 미등록');$('location-source').textContent='브라우저 위치 · 서버 미등록';note('브라우저 위치를 입력했습니다. 라즈베리파이 옆에서 측정했는지 확인한 뒤 서버에 등록하세요.');},err=>note(`브라우저 위치를 읽지 못했습니다: ${err.message}`,true),{enableHighAccuracy:true,timeout:15000,maximumAge:0});}
async function estimateGreen(){const p=position();if(!p){note('장치 위치를 먼저 입력하거나 서버에서 조회하세요.',true);return;}const button=$('estimate-green');button.disabled=true;$('green-detail').textContent='OpenStreetMap 녹지 자료 조회 및 면적 계산 중…';try{const result=await GreenArea.fetchEstimate(p);lastGreenPosition=p;$('green-value').textContent=fmt(result.squareMetres,0)+' m²';const selection=result.selectionMode==='contains'?'장치가 속한 녹지 1개':result.selectionMode==='nearest'?`장치에서 약 ${fmt(result.distanceMetres,0)} m 떨어진 녹지 1개`:'장치 위치 또는 30 m 이내에 등록된 녹지가 없습니다';$('green-detail').textContent=`${selection} · 장치 중심 반경 ${result.radiusMetres} m 이내 ${fmt(result.squareMetres/10000,3)} ha. 지도 등록 경계의 추정값이며 영상 자동 판독 결과는 아닙니다.`;if(map){if(greenLayer)map.removeLayer(greenLayer);greenLayer=L.layerGroup([L.circle(p,{radius:result.radiusMetres,color:'#279b56',weight:2,fillOpacity:0,dashArray:'5 5'}),...result.patches.map(bounds=>L.rectangle(bounds,{stroke:false,fillColor:'#46ba68',fillOpacity:.35}))]).addTo(map);}note(result.mappedPolygons?'장치 인근 녹지 한 구역의 면적을 추산했습니다.':'가까운 등록 녹지가 없습니다. 위성영상에서 경계를 직접 지정할 수 있습니다.');}catch(err){$('green-value').textContent='— m²';$('green-detail').textContent=err.message;note(err.message,true);}finally{button.disabled=false;}}
$('browser-location').onclick=browserLocation;$('publish-location').onclick=publishLocation;$('refresh-location').onclick=refreshLocation;$('estimate-green').onclick=estimateGreen;
form.addEventListener('submit',event=>event.preventDefault());form.addEventListener('input',render);for(const id of ['lat','lon']){$(id).addEventListener('input',render);$(id).addEventListener('change',()=>{const p=position();if(map&&p)map.setView(p,16);});}$('add-tree').onclick=()=>{if(groups().length>=50){note('수종 그룹은 최대 50개입니다.',true);return;}addTree();render();};$('center-map').onclick=()=>{const p=position();if(!p){note('장치 좌표를 먼저 등록하세요.',true);return;}if(map)map.setView(p,16);};$('undo-point').onclick=()=>{vertices.pop();render();};$('clear-points').onclick=()=>{vertices=[];render();};$('save').onclick=()=>{try{localStorage.setItem(key,JSON.stringify(snapshot()));note('위치·경계·수목 입력을 이 브라우저에 저장했습니다.');}catch{note('브라우저 저장소를 사용할 수 없습니다.',true);}};$('sample').onclick=()=>{$('date0').value='2025-09-22';$('date1').value='2026-09-22';$('tree-groups').replaceChildren();addTree({species:'소나무 · 예시',n0:20,n1:20,d0:20,d1:20.8,h0:8,h1:8.3});render();note('수목 입력 예시만 표시했습니다. 장치 위치와 센서값은 실제 정보가 들어올 때까지 비워 둡니다.');};$('refresh-readings').onclick=refresh;$('device').onchange=()=>{records=[];sensorCards();render();};setInterval(()=>{if($('admin-token').value.trim())refresh();},21600000);
try{const saved=localStorage.getItem(key);if(saved)restore(JSON.parse(saved));else{addTree();render();}}catch{addTree();render();note('저장된 입력을 불러올 수 없어 새 화면으로 시작했습니다.',true);}sensorCards();initMap();



