 'use strict';
window.WithUAuth=(()=>{
 let user=null;
 async function request(path,method='GET',body){const response=await fetch(path,{method,credentials:'same-origin',headers:body?{'Content-Type':'application/json'}:{},body:body?JSON.stringify(body):undefined,cache:'no-store'});const data=await response.json().catch(()=>({}));if(!response.ok){const error=Object.assign(Error(data.error||'서버 요청 실패'),{status:response.status});if(response.status===401&&path!=='/api/auth'&&user){user=null;window.dispatchEvent(new Event('withu-auth'));}throw error;}return data;}
 const dialog=document.createElement('dialog');dialog.className='account-dialog';dialog.setAttribute('aria-labelledby','account-title');dialog.innerHTML=`<form id="account-form"><div class="account-heading"><h2 id="account-title">기업 로그인</h2><button type="button" id="close-account" aria-label="닫기">×</button></div><label>아이디<input name="username" autocomplete="username" minlength="3" maxlength="50" required></label><label>비밀번호<input name="password" type="password" autocomplete="current-password" maxlength="72" required></label><fieldset id="signup-fields" hidden disabled><label>기업명<input name="name" maxlength="120" required></label><label>사업장·보고 경계<input name="boundary" maxlength="500" placeholder="예: 서울 본사 및 제1공장" required></label></fieldset><p id="account-error" role="alert"></p><button type="submit" class="primary" id="account-submit">로그인</button><button type="button" id="signup-toggle">기업 회원가입</button><button type="button" id="admin-login" class="account-admin-link">관리자 로그인</button><button type="button" id="company-login-toggle" hidden>기업 로그인으로 돌아가기</button></form>`;document.body.append(dialog);
 const form=dialog.querySelector('form'),title=dialog.querySelector('#account-title'),fields=dialog.querySelector('fieldset'),toggle=dialog.querySelector('#signup-toggle'),submit=dialog.querySelector('#account-submit'),adminToggle=dialog.querySelector('#admin-login'),companyToggle=dialog.querySelector('#company-login-toggle');let mode='login';
 function apply(){const signup=mode==='signup',admin=mode==='admin-login';title.textContent=signup?'기업 회원가입':admin?'관리자 로그인':'기업 로그인';fields.hidden=fields.disabled=!signup;toggle.hidden=admin;adminToggle.hidden=admin;companyToggle.hidden=!admin;toggle.textContent=signup?'기업 로그인으로 돌아가기':'기업 회원가입';submit.textContent=signup?'회원가입':'로그인';form.elements.password.autocomplete=signup?'new-password':'current-password';form.elements.password.minLength=signup?8:1;}
 function open(admin=false){mode=admin?'admin-login':'login';form.reset();dialog.querySelector('#account-error').textContent='';apply();dialog.showModal();form.elements.username.focus();}
 toggle.onclick=()=>{mode=mode==='signup'?'login':'signup';apply();};dialog.querySelector('#close-account').onclick=()=>dialog.close();
 adminToggle.onclick=()=>{mode='admin-login';form.reset();dialog.querySelector('#account-error').textContent='';apply();form.elements.username.focus();};
 companyToggle.onclick=()=>{mode='login';form.reset();dialog.querySelector('#account-error').textContent='';apply();form.elements.username.focus();};
 form.onsubmit=async ev=>{ev.preventDefault();submit.disabled=true;dialog.querySelector('#account-error').textContent='';try{const data=await request('/api/auth','POST',{...Object.fromEntries(new FormData(form)),action:mode});user=data.user;form.reset();dialog.close();if(user.role==='admin'){location.href='admin.html';return;}window.dispatchEvent(new Event('withu-auth'));}catch(e){dialog.querySelector('#account-error').textContent=e.message;}finally{submit.disabled=false;}};
 async function check(){try{const result=await request('/api/auth');user=result.user;return result;}catch(e){user=null;if(e.status!==401)throw e;return {user:null};}}
 async function logout(){await request('/api/auth','POST',{action:'logout'});user=null;window.dispatchEvent(new Event('withu-auth'));}
 return {request,open,check,logout,get user(){return user;}};
})();
